// <auto-generated />
using LogicStoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicStoreAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230111220812_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicStoreAPI.Models.ItemPicture", b =>
                {
                    b.Property<int>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PictureId"));

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<string>("PictureString")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("PictureId");

                    b.ToTable("ItemPictures");
                });

            modelBuilder.Entity("LogicStoreAPI.Models.StoreItem", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<float>("ItemCost")
                        .HasColumnType("real");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ItemPicture")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<float>("ItemPrice")
                        .HasColumnType("real");

                    b.Property<string>("ItemSKU")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("ItemWeight")
                        .HasColumnType("real");

                    b.HasKey("ItemID");

                    b.ToTable("StoreItems");
                });
#pragma warning restore 612, 618
        }
    }
}
